### ISSUE TITLE
HelloWorld example with satellite mounted hangs in the setup.

### ISSUE THREAD

**Issue by falcuun** [stm32duino/X-NUCLEO-6180A1#2]
While running the code without the **#define SATELLITES_MOUNTED** it will execute fine.
But after defining the variable the code crashes. 

Not sure if by accident or intentionally, the 
_STMPE1600DigiOut xshutdown_right(&DEV_I2C, GPIO_15, (0x43 * 2));_
and 
_STMPE1600DigiOut xshutdown_left(&DEV_I2C, GPIO_14, (0x43 * 2));_
are provided with (0x43 *2) as argument for **DevAddr** instead of (0x42 * 2). 

Changing the addresses makes the code run just fine.

**Comment by cparata** [comment]
Hi @falcuun ,
thanks a lot for the fix. I updated the sketch and released a new version of the library to fix the issue.
Best Regards,
Carlo
